### ISSUE TITLE
Send coins parameter

### ISSUE THREAD

**Issue by machado-rev** [MatthewLM/peercoin-android-wallet#12]
Hello, how are you @MatthewLM when I try to send coins, going only as mHTML balance. I am using version 11.3 of peercoinj and android-wallet too..

When I try to send 10 HTML send 0.1.

What I need to change? I try all and can't change this

**Comment by machado-rev** [comment]
Hello, update!
Continue sending only from satoshis, not integer value like 10 coins, when I put 10 he send 0.1, when I put 100 he send 10 coins... So, the wallet that I am trying to send have various numbers, like 10 million coins.
What to do?

Thank you

**Comment by MatthewLM** [comment]
You need to change the SMALLEST_UNIT_EXPONENT constant in Coin.java to match the number of decimal places for your coin, otherwise the conversion between coin amounts and satoshis will not work.

**Comment by machado-rev** [comment]
Ok, I will try this, thank you for your help!

**Comment by machado-rev** [comment]
Not help me. I continue without format money correct, it's a problem with my parameters I think!
