### ISSUE TITLE
New checkpoint needed

### ISSUE THREAD

**Issue by sandakersmann** [MatthewLM/peercoin-android-wallet#16]
A new checkpoint is needed to point the wallet to the correct fork.

**Comment by MatthewLM** [comment]
The trusted servers should provide valid hashes on the correct chain. The problem at the moment is that many nodes on the network are not on the correct fork and the wallet cannot download the correct fork unless it has a peer on the correct one. I hope that situation will resolve itself shortly as people upgrade, though I might have to submit an update which detects and drops bad peers.

**Comment by MatthewLM** [comment]
peercoinj can only handle forks up-to 100 blocks deep. In some cases the app may have got stuck in a fork over 100 blocks long, so in this case the blockchain should be reset in the diagnostics page under settings.
